; Auto-generated. Do not edit!


(cl:in-package panda_demo-msg)


;//! \htmlinclude GsResult.msg.html

(cl:defclass <GsResult> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass GsResult (<GsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name panda_demo-msg:<GsResult> is deprecated: use panda_demo-msg:GsResult instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <GsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader panda_demo-msg:distance-val is deprecated.  Use panda_demo-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GsResult>) ostream)
  "Serializes a message object of type '<GsResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GsResult>) istream)
  "Deserializes a message object of type '<GsResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GsResult>)))
  "Returns string type for a message object of type '<GsResult>"
  "panda_demo/GsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GsResult)))
  "Returns string type for a message object of type 'GsResult"
  "panda_demo/GsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GsResult>)))
  "Returns md5sum for a message object of type '<GsResult>"
  "6e77fb10f0c8b4833ec273aa9ac74459")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GsResult)))
  "Returns md5sum for a message object of type 'GsResult"
  "6e77fb10f0c8b4833ec273aa9ac74459")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GsResult>)))
  "Returns full string definition for message of type '<GsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GsResult)))
  "Returns full string definition for message of type 'GsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GsResult
    (cl:cons ':distance (distance msg))
))
