// Generated by gencpp from file panda_demo/GsGoal.msg
// DO NOT EDIT!


#ifndef PANDA_DEMO_MESSAGE_GSGOAL_H
#define PANDA_DEMO_MESSAGE_GSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_demo
{
template <class ContainerAllocator>
struct GsGoal_
{
  typedef GsGoal_<ContainerAllocator> Type;

  GsGoal_()
    {
    }
  GsGoal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::panda_demo::GsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_demo::GsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GsGoal_

typedef ::panda_demo::GsGoal_<std::allocator<void> > GsGoal;

typedef boost::shared_ptr< ::panda_demo::GsGoal > GsGoalPtr;
typedef boost::shared_ptr< ::panda_demo::GsGoal const> GsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_demo::GsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_demo::GsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace panda_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_demo::GsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_demo::GsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_demo::GsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_demo::GsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_demo::GsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_demo::GsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_demo::GsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::panda_demo::GsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_demo::GsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_demo/GsGoal";
  }

  static const char* value(const ::panda_demo::GsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_demo::GsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
;
  }

  static const char* value(const ::panda_demo::GsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_demo::GsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_demo::GsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::panda_demo::GsGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_DEMO_MESSAGE_GSGOAL_H
