// Generated by gencpp from file panda_demo/GsResult.msg
// DO NOT EDIT!


#ifndef PANDA_DEMO_MESSAGE_GSRESULT_H
#define PANDA_DEMO_MESSAGE_GSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_demo
{
template <class ContainerAllocator>
struct GsResult_
{
  typedef GsResult_<ContainerAllocator> Type;

  GsResult_()
    : distance(0.0)  {
    }
  GsResult_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::panda_demo::GsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_demo::GsResult_<ContainerAllocator> const> ConstPtr;

}; // struct GsResult_

typedef ::panda_demo::GsResult_<std::allocator<void> > GsResult;

typedef boost::shared_ptr< ::panda_demo::GsResult > GsResultPtr;
typedef boost::shared_ptr< ::panda_demo::GsResult const> GsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_demo::GsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_demo::GsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_demo::GsResult_<ContainerAllocator1> & lhs, const ::panda_demo::GsResult_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_demo::GsResult_<ContainerAllocator1> & lhs, const ::panda_demo::GsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_demo::GsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_demo::GsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_demo::GsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_demo::GsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_demo::GsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_demo::GsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_demo::GsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::panda_demo::GsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_demo::GsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_demo/GsResult";
  }

  static const char* value(const ::panda_demo::GsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_demo::GsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"float32 distance\n"
;
  }

  static const char* value(const ::panda_demo::GsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_demo::GsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_demo::GsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_demo::GsResult_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_DEMO_MESSAGE_GSRESULT_H
